apiVersion: apps/v1
kind: Deployment
metadata:
  name: notificacao-dep
  namespace: fast-video
  labels:
    app: notificacao
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notificacao
  template:
    metadata:
      labels:
        app: notificacao
    spec:
      containers:
      - name: notificacao-cont
        image: sickbanger/notificacao:latest
        ports:
        - containerPort: 5271
        - containerPort: 7205
        envFrom:
          - configMapRef:
              name: notificacao-configmap
        livenessProbe:
          httpGet:
            path: /health
            port: 5271
          initialDelaySeconds: 20
          periodSeconds: 10
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 5271
          initialDelaySeconds: 10
          periodSeconds: 5
          failureThreshold: 3
        resources:
          requests:
            cpu: "100m"
            memory: "256Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
