apiVersion: apps/v1
kind: Deployment
metadata:
  name: notificacao-api
  namespace: fast-video
spec:
  replicas: 2
  selector:
    matchLabels:
      app: notificacao-api
  template:
    metadata:
      labels:
        app: notificacao-api
    spec:
      serviceAccountName: notificacao-api-sa
      containers:
        - name: notificacao-api
          image: sickbanger/notificacao-api:latest
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: notificacao-config
            - secretRef:
                name: notificacao-secrets
          readinessProbe:
            httpGet:
              path: /swagger/index.html
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /swagger/index.html
              port: 80
            initialDelaySeconds: 15
            periodSeconds: 10
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "250m"
              memory: "256Mi"
