apiVersion: v1
kind: Service
metadata:
  name: notificacao-api
  namespace: fast-video
spec:
  selector:
    app: notificacao-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
