apiVersion: v1
kind: Service
metadata:
  name: notificacao-svc
  namespace: fast-video
spec:
  selector:
    app: notificacao
  type: LoadBalancer
  ports:
    - port: 80
      name: http
      targetPort: 5271
