name: CI/CD Build & Deploy

on:
  push:
    branches:
      - main

jobs:
  build-push-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup .NET 8
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: |
          cd src/Notificacao.Api
          dotnet restore Notificacao.Api.csproj

      - name: Build and publish
        run: |
          cd src/Notificacao.Api
          dotnet publish Notificacao.Api.csproj -c Release -o app/publish /p:UseAppHost=false

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/notificacao-api:latest \
                       -t ${{ secrets.DOCKER_USERNAME }}/notificacao-api:${{ github.sha }} .

      - name: Push Docker images to Docker Hub
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/notificacao-api:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/notificacao-api:${{ github.sha }}

      - name: Install kubectl
        run: |
          curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
          chmod +x kubectl
          sudo mv kubectl /usr/local/bin/

      - name: Install AWS CLI
        run: |
          sudo apt-get update && sudo apt-get install -y awscli

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: us-east-1

      - name: Update kubeconfig for AWS EKS
        run: |
          aws eks update-kubeconfig --region us-east-1 --name techchalenge-eks-cluster

      - name: Deploy to EKS Cluster
        run: |
          kubectl apply -f iac/kubernetes/namespace.yaml
          kubectl apply -f iac/kubernetes
          kubectl rollout status deployment/Notificacao-dep -n fast-order
